name: Publish PDFs

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LATEX: /usr/bin/latexmk
      OUTPUT_DIR: .

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install
      uses: pandoc/actions/setup@v1
      with:
        version: 2.19

    - name: Show pandoc version
      run: pandoc --version

    - name: Install .svg tools
      run: sudo apt-get update && sudo apt-get install librsvg2-bin

    - name: Build pdfs
      run: make -C ./proj3/
      
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        draft: false
        prerelease: false

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.OUTPUT_DIR }}/*.pdf
        tag: ${{ steps.tag_version.outputs.new_tag }}
        overwrite: true
        file_glob: true